version: "3.8"

services:
  db:
    image: postgres:13
    container_name: matcha_db
    environment:
      POSTGRES_DB: matcha
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: matcha
    ports:
      - "5432:5432"
    volumes:
      - matcha_db_data:/var/lib/postgresql/data

volumes:
  matcha_db_data:
